[dr]
type = drive
scope = drive
token = {"access_token":"ya29.A0ARrdaM_3yGZld2B-CZsf9dV23XibylvF6aiBiljMK","token_type":"Bearer","refresh_token":"1//0g5ypCWFJM6-WCgYIARAAGBASNwF-H0M21qhTPs07UROHRw5j7zKTr7PZk","expiry":"2022-02-01T08:15:07.750849333+07:00"}
root_folder_id = 0AHM2d9PVA
